name: Descobrir Home FTP

on:
  push:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Descobrir home FTP
        run: |
          lftp -c "
            set ftp:passive-mode true;
            set ssl:verify-certificate no;
            open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' ftp://ftp.ibnfamily.com.br;

            echo '=== PWD ===';
            pwd;

            echo '=== LISTAGEM ===';
            cls -la;

            echo '=== HOME ===';
            cd ~;
            pwd;
            cls -la;
          "