name: Testar FTP

on:
  push:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Testar diretório FTP
        run: |
          lftp -c "
            set ftp:passive-mode true;
            set ssl:verify-certificate no;
            set net:timeout 10;
            set net:max-retries 1;
            open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' ftp://ftp.ibnfamily.com.br;
            pwd;
          "